"""Initial migration with performance indexes.

Revision ID: 0d3c083c2b7d
Revises: 88021398f4b4
Create Date: 2025-09-22 12:05:33.715160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3c083c2b7d'
down_revision = '88021398f4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_line_message_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_is_outgoing'), ['is_outgoing'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_line_account_id'), ['line_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_line_account_id'), ['line_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_phone'), ['phone'], unique=False)

    with op.batch_alter_table('quick_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quick_reply_line_account_id'), ['line_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quick_reply_shortcut'), ['shortcut'], unique=False)

    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.create_index('ix_package_sticker', ['packageId', 'stickerId'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))

    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.drop_index('ix_package_sticker')

    with op.batch_alter_table('quick_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quick_reply_shortcut'))
        batch_op.drop_index(batch_op.f('ix_quick_reply_line_account_id'))

    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_user_phone'))
        batch_op.drop_index(batch_op.f('ix_line_user_line_account_id'))
        batch_op.drop_index(batch_op.f('ix_line_user_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_line_user_created_at'))

    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_line_message_message_type'))
        batch_op.drop_index(batch_op.f('ix_line_message_line_account_id'))
        batch_op.drop_index(batch_op.f('ix_line_message_is_outgoing'))
        batch_op.drop_index(batch_op.f('ix_line_message_admin_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
