"""Add is_active to LineAccount with default

Revision ID: 38d75f94b5a7
Revises: 
Create Date: 2025-09-27 11:40:50.965105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d75f94b5a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('channel_secret', sa.String(length=255), nullable=False),
    sa.Column('channel_access_token', sa.String(length=255), nullable=False),
    sa.Column('webhook_path', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_check_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_check_status_message', sa.String(), nullable=True),
    sa.Column('manager_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('webhook_path')
    )
    with op.batch_alter_table('line_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_account_is_active'), ['is_active'], unique=False)

    op.create_table('oa_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packageId', sa.String(length=50), nullable=False),
    sa.Column('stickerId', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.create_index('ix_package_sticker', ['packageId', 'stickerId'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('line_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('line_account_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_url', sa.String(length=255), nullable=True),
    sa.Column('media_key', sa.String(length=512), nullable=True),
    sa.Column('sticker_id', sa.String(length=50), nullable=True),
    sa.Column('package_id', sa.String(length=50), nullable=True),
    sa.Column('is_outgoing', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('line_sent_successfully', sa.Boolean(), nullable=False),
    sa.Column('line_error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['line_account_id'], ['line_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_message_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_is_outgoing'), ['is_outgoing'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_line_account_id'), ['line_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_media_key'), ['media_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_message_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_line_message_user_time', ['user_id', 'timestamp'], unique=False)

    op.create_table('line_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('line_account_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=1024), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_read_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['line_account_id'], ['line_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_account_id', 'user_id', name='_line_account_user_uc')
    )
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_is_blocked'), ['is_blocked'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_line_account_id'), ['line_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_status'), ['status'], unique=False)

    op.create_table('oa_group_association',
    sa.Column('line_account_id', sa.Integer(), nullable=False),
    sa.Column('oa_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_account_id'], ['line_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oa_group_id'], ['oa_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_account_id', 'oa_group_id')
    )
    op.create_table('quick_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortcut', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('line_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_account_id'], ['line_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quick_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quick_reply_line_account_id'), ['line_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quick_reply_shortcut'), ['shortcut'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quick_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quick_reply_shortcut'))
        batch_op.drop_index(batch_op.f('ix_quick_reply_line_account_id'))

    op.drop_table('quick_reply')
    op.drop_table('oa_group_association')
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_user_status'))
        batch_op.drop_index(batch_op.f('ix_line_user_phone'))
        batch_op.drop_index(batch_op.f('ix_line_user_line_account_id'))
        batch_op.drop_index(batch_op.f('ix_line_user_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_line_user_is_blocked'))
        batch_op.drop_index(batch_op.f('ix_line_user_created_at'))

    op.drop_table('line_user')
    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.drop_index('ix_line_message_user_time')
        batch_op.drop_index(batch_op.f('ix_line_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_line_message_message_type'))
        batch_op.drop_index(batch_op.f('ix_line_message_media_key'))
        batch_op.drop_index(batch_op.f('ix_line_message_line_account_id'))
        batch_op.drop_index(batch_op.f('ix_line_message_is_outgoing'))
        batch_op.drop_index(batch_op.f('ix_line_message_admin_user_id'))

    op.drop_table('line_message')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))

    op.drop_table('user')
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.drop_index('ix_package_sticker')

    op.drop_table('sticker')
    op.drop_table('oa_group')
    with op.batch_alter_table('line_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_account_is_active'))

    op.drop_table('line_account')
    # ### end Alembic commands ###
