"""Add last_message_at to LineUser model

Revision ID: 43269bb2896a
Revises: a0875033dc31
Create Date: 2025-10-03 16:05:55.163666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43269bb2896a'
down_revision = 'a0875033dc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_line_user_last_seen_at'))
        batch_op.create_index(batch_op.f('ix_line_user_last_message_at'), ['last_message_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_user_last_message_at'))
        batch_op.create_index(batch_op.f('ix_line_user_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.drop_column('last_message_at')

    # ### end Alembic commands ###
