"""add media_key to LineMessage

Revision ID: 6d151b3361d7
Revises: 0d3c083c2b7d
Create Date: 2025-09-22 16:28:15.639763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d151b3361d7'
down_revision = '0d3c083c2b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_key', sa.String(length=512), nullable=True))
        batch_op.create_index(batch_op.f('ix_line_message_media_key'), ['media_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_message_media_key'))
        batch_op.drop_column('media_key')

    # ### end Alembic commands ###
