"""add read_by to lineuser

Revision ID: 8b15f7c4c0e8
Revises: 8d179bc85aa2
Create Date: 2025-10-14 17:29:56.726728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b15f7c4c0e8'
down_revision = '8d179bc85aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_by_admin_id', sa.Integer(), nullable=True))
        # ★★★ แก้ไขบรรทัดนี้ ★★★
        batch_op.create_foreign_key('fk_line_user_read_by_admin', 'user', ['read_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('read_by_admin_id')

    # ### end Alembic commands ###
