"""Add manager_url to LineAccount

Revision ID: a28db7ed2bd5
Revises: 6d151b3361d7
Create Date: 2025-09-23 14:18:54.741029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28db7ed2bd5'
down_revision = '6d151b3361d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_message_account_time'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_message_account_time'), ['line_account_id', sa.literal_column('timestamp DESC')], unique=False)

    with op.batch_alter_table('line_account', schema=None) as batch_op:
        batch_op.drop_column('manager_url')

    # ### end Alembic commands ###
