"""Add is_active to User with server_default

Revision ID: f8e2732b68ad
Revises: 43269bb2896a
Create Date: 2025-10-07 17:06:30.737951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e2732b68ad'
down_revision = '43269bb2896a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_line_user_last_seen_at'))
        batch_op.create_index(batch_op.f('ix_line_user_last_message_at'), ['last_message_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('line_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_user_last_message_at'))
        batch_op.create_index(batch_op.f('ix_line_user_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.drop_column('last_message_at')

    # ### end Alembic commands ###
